Imports System.IO
Imports System.Text.RegularExpressions

Public Class Form1
    Private filepath_src As String = Nothing
    Private src_gcode As String = Nothing
    Private new_gcode As String = Nothing
    Private Utils_ As Utils
    Private slicer_name As String = Nothing
    Dim fan_speeds() As Integer = {100, 100, 100, 100, 100, 100}
    Dim fan_speeds_tmp() As Integer = {100, 100, 100, 100, 100, 100}
    Dim fans_speed_linked As Boolean = True

    Dim hotend_temp() As Integer = {210, 205, 200, 195, 190, 185}
    Dim hotend_temp_tmp() As Integer = {210, 205, 200, 195, 190, 185}
    Dim hotend_temps_linked As Boolean = False

    Dim heatbed_temp() As Integer = {70, 70, 70, 70, 70, 70}
    Dim heatbed_temp_tmp() As Integer = {70, 70, 70, 70, 70, 70}
    Dim heatbed_temp_linked As Boolean = True

    Dim flowrate() As Integer = {100, 100, 100, 100, 100, 100}
    Dim flowrate_tmp() As Integer = {100, 100, 100, 100, 100, 100}
    Dim flowrate_linked As Boolean = True

    Dim GcodeViewEnable As Boolean = False
    Dim layers() As Integer = {9, 28, 48, 68, 88, 108}
    Dim skip_1 As Boolean = False
    Private loaded As Boolean = False
    Dim lb As RichTextBox
    Private print_speed As Integer()
    Private print_speed_linked As Boolean
    Private layer_nbr_afterbase As Integer


    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        ComboBox1.SelectedIndex = 0
        PictureBox1.Image = ImageList1.Images(0)
        PictureBox2.Image = ImageList1.Images(1)
        PictureBox3.Image = ImageList1.Images(1)
        PictureBox4.Image = ImageList1.Images(1)
        Utils_ = New Utils
        RichTextBox2.BackColor = Color.White
        lb = New RichTextBox
        lb.Enabled = True
        RichTextBox2.Controls.Add(lb)
        'lb.Dock = DockStyle.Right
        lb.BorderStyle = BorderStyle.None
        lb.Width = RichTextBox2.Width - 20
        lb.Height = RichTextBox2.Height - 20
        lb.Top = 10
        lb.Left = 10
        '  lb.BackColor = Color.Red
        lb.AutoSize = False
        lb.Text = String.Empty

    End Sub

    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        slicer_name = Nothing
        filepath_src = Nothing
        src_gcode = Nothing
        Try
            With OpenFileDialog1
                .FileName = ""
                .DefaultExt = "gcode"
                .ShowDialog()
            End With

            RichTextBox1.Text = OpenFileDialog1.FileName
            filepath_src = OpenFileDialog1.FileName
            If File.Exists(filepath_src) Then
                src_gcode = Utils_.ReadGcode(filepath_src)
                If src_gcode.Contains("generated by Simplify3D") = True Then
                    slicer_name = "Simplify3D"
                ElseIf src_gcode.Contains(";Generated with Cura") Then
                    slicer_name = "Cura Engine"
                ElseIf src_gcode.Contains("generated by Slic3r") Then
                    slicer_name = "Slic3r - Not yet supported without custom layer gcode.."
                    Label3.Text = slicer_name
                    If src_gcode.Contains(";LAYER:") Then
                        slicer_name = "Slic3r with custom ""before layer change"" gcode"
                    Else
                        Label4.Text = "Slic3r is not currently supported without custom before layer change gcode: "";LAYER:[layer_num]"""
                        Exit Sub
                    End If


                End If
                Label3.Text = slicer_name
            Else
                Label4.Text = "Loading canceled.."
                Exit Sub
            End If

        Catch
            Label4.Text = "Error ..."
            Exit Sub
        End Try
        Label4.Text = "Gcode Loaded"
    End Sub

    Private Sub Button2_Click(sender As Object, e As EventArgs) Handles Button2.Click
        Try
            If new_gcode Is Nothing Then
                MsgBox("Apply new temps before saving..")
            Else
                With SaveFileDialog1
                    .FileName = "New_stl_tower"
                    .DefaultExt = "gcode"
                    .ShowDialog()
                End With
                filepath_src = SaveFileDialog1.FileName

                Utils_.WriteGcode(filepath_src, new_gcode)
                Label4.Text = "Gcode saved to " & filepath_src & ""
            End If
        Catch
            Label4.Text = "Error ..."
            Exit Sub
        End Try

    End Sub

    Private Sub linkLabel1_LinkClicked(ByVal sender As Object,
                ByVal e As System.Windows.Forms.LinkLabelLinkClickedEventArgs) Handles LinkLabel1.LinkClicked
        Me.LinkLabel1.Links(0).LinkData = "https://github.com/ketchu13"
        Dim target As String = CType(e.Link.LinkData, String)
        If (target IsNot Nothing) Then
            System.Diagnostics.Process.Start(target)
        Else
            'MessageBox.Show(("Visit " + target))
        End If

    End Sub

    Private Sub Button3_Click(sender As Object, e As EventArgs) Handles Button3.Click
        new_gcode = Nothing
        ' Try
        hotend_temp = {Val(TextBox3.Text), Val(TextBox4.Text), Val(TextBox5.Text), Val(TextBox6.Text), Val(TextBox7.Text), Val(TextBox8.Text)}
            heatbed_temp = {Val(TextBox27.Text), Val(TextBox28.Text), Val(TextBox29.Text), Val(TextBox30.Text), Val(TextBox31.Text), Val(TextBox32.Text)}
            fan_speeds = {Val(TextBox13.Text), Val(TextBox14.Text), Val(TextBox15.Text), Val(TextBox16.Text), Val(TextBox17.Text), Val(TextBox18.Text)}
            layers = {Val(TextBox3t.Text), Val(TextBox4t.Text), Val(TextBox5t.Text), Val(TextBox6t.Text), Val(TextBox7t.Text), Val(TextBox8t.Text)}
            fan_speeds = Utils_.ConvertPercentToH(fan_speeds) 'todo check values
            flowrate = {Val(TextBox20.Text), Val(TextBox22.Text), Val(TextBox23.Text), Val(TextBox24.Text), Val(TextBox25.Text), Val(TextBox26.Text)}

            If src_gcode Is Nothing Then
                Label4.Text = ("You must load first a gcode file before apply new settings...")
                Exit Sub
            Else
            new_gcode = Utils_.ReplaceSettings(hotend_temp, hotend_temps_linked,
                                               heatbed_temp, heatbed_temp_linked,
                                               flowrate, flowrate_linked,
                                               print_speed, print_speed_linked,
                                               fan_speeds, fans_speed_linked,
                                               src_gcode, slicer_name,
                                               layer_nbr_afterbase, layers)
        End If
        ' Catch
        'Label4.Text = "Error ..."
        'Exit Sub
        'End Try
        Label4.Text = "New settings applied ... Don't forget to save.."

    End Sub

    Private Sub Button4_Click(sender As Object, e As EventArgs) Handles Button4.Click
        GcodeViewEnable = Not GcodeViewEnable
        If GcodeViewEnable Then
            Button4.Text = "Hide Gcodes"
            Me.Size = New Size(Me.Width, 347 + RichTextBox2.Height + 10)
            ' GroupBox2.Size = New Size(667, 507)
            If new_gcode Is Nothing Then
                lb.Text = src_gcode
            Else
                lb.Text = new_gcode
            End If
            If new_gcode Is Nothing And src_gcode Is Nothing Then
                Label4.Text = "You must load a gcode file before view it..."
            End If
        Else
            Me.Size = New Size(Me.Width, 347)
            ' GroupBox2.Size = New Size(634, 45)
            Button4.Text = "Show Gcodes"
        End If
    End Sub

    Private Sub Timer1_Tick(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Timer1.Tick
        If (RichTextBox2.Focused) Then
            lb.Focus()
        End If
    End Sub

    Private Sub Button5_Click(sender As Object, e As EventArgs) Handles Button5.Click
        fan_speeds = {Val(TextBox13.Text), Val(TextBox14.Text), Val(TextBox15.Text), Val(TextBox16.Text), Val(TextBox17.Text), Val(TextBox18.Text)}

    End Sub

    Private Sub TextBox13_KeyPress(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyPressEventArgs) Handles TextBox13.KeyPress, TextBox14.KeyPress, TextBox15.KeyPress, TextBox16.KeyPress, TextBox17.KeyPress, TextBox18.KeyPress,
        TextBox3.KeyPress, TextBox4.KeyPress, TextBox5.KeyPress, TextBox6.KeyPress, TextBox7.KeyPress, TextBox8.KeyPress,
        TextBox3t.KeyPress, TextBox4t.KeyPress, TextBox5t.KeyPress, TextBox6t.KeyPress, TextBox7t.KeyPress, TextBox8t.KeyPress,
        TextBox27.KeyPress, TextBox28.KeyPress, TextBox29.KeyPress, TextBox30.KeyPress, TextBox31.KeyPress, TextBox32.KeyPress,
        TextBox20.KeyPress, TextBox21.KeyPress, TextBox22.KeyPress, TextBox23.KeyPress, TextBox24.KeyPress, TextBox25.KeyPress

        If Not Char.IsNumber(e.KeyChar) AndAlso Not Char.IsControl(e.KeyChar) Then
            e.Handled = True
        End If
    End Sub

    Private Sub TextBox13_TextChanged(sender As Object, e As EventArgs) Handles TextBox13.TextChanged, TextBox14.TextChanged, TextBox15.TextChanged, TextBox16.TextChanged, TextBox17.TextChanged, TextBox18.TextChanged
        If loaded Then
        Else
            Exit Sub
        End If
        If sender.name.ToString.Length > 0 And Not fan_speeds Is Nothing Then


            Dim digitsOnly As Regex = New Regex("[^\d]")
            sender.Text = digitsOnly.Replace(sender.Text, "")
            If fans_speed_linked Then
                fan_speeds(0) = Math.Max(0, Math.Min(100, Val(TextBox13.Text)))
                fan_speeds_tmp(0) = Math.Max(0, Math.Min(100, Val(TextBox13.Text)))
                sender.Text = fan_speeds(0)
                For i As Integer = 14 To 18
                    Dim txt As TextBox = Me.Controls("GroupBox1").Controls("TextBox" & i)
                    txt.Text = fan_speeds(0)
                Next
            Else
                Select Case sender.name
                    Case "TextBox13"
                        fan_speeds(0) = Math.Min(100, Val(sender.text))
                        fan_speeds_tmp(0) = Math.Min(100, Val(sender.text))
                    Case "TextBox14"
                        fan_speeds(1) = Math.Min(100, Val(sender.text))
                        fan_speeds_tmp(1) = Math.Min(100, Val(sender.text))
                    Case "TextBox15"
                        fan_speeds(2) = Math.Min(100, Val(sender.text))
                        fan_speeds_tmp(2) = Math.Min(100, Val(sender.text))
                    Case "TextBox16"
                        fan_speeds(3) = Math.Min(100, Val(sender.text))
                        fan_speeds_tmp(3) = Math.Min(100, Val(sender.text))
                    Case "TextBox17"
                        fan_speeds(4) = Math.Min(100, Val(sender.text))
                        fan_speeds_tmp(4) = Math.Min(100, Val(sender.text))
                    Case "TextBox18"
                        fan_speeds(5) = Math.Min(100, Val(sender.text))
                        fan_speeds_tmp(5) = Math.Min(100, Val(sender.text))
                End Select

            End If
        End If
    End Sub

    Private Sub TextBox27_TextChanged(sender As Object, e As EventArgs) Handles TextBox27.TextChanged, TextBox28.TextChanged, TextBox29.TextChanged, TextBox30.TextChanged, TextBox31.TextChanged, TextBox32.TextChanged
        If loaded Then
        Else
            Exit Sub
        End If
        If sender.name.ToString.Length > 0 And Not heatbed_temp Is Nothing Then
            Dim digitsOnly As Regex = New Regex("[^\d]")
            sender.Text = digitsOnly.Replace(sender.Text, "")
            If heatbed_temp_linked Then
                heatbed_temp(0) = Math.Min(130, Val(TextBox27.Text))
                heatbed_temp_tmp(0) = Math.Min(130, Val(TextBox27.Text))
                sender.Text = heatbed_temp(0)
                For i As Integer = 28 To 32
                    Dim txt As TextBox = Me.Controls("GroupBox1").Controls("TextBox" & i)
                    txt.Text = heatbed_temp(0)
                Next
            Else
                Select Case sender.name
                    Case "TextBox27"
                        heatbed_temp(0) = Math.Min(130, Val(sender.text))
                        heatbed_temp_tmp(0) = Math.Min(130, Val(sender.text))
                    Case "TextBox28"
                        heatbed_temp(1) = Math.Min(130, Val(sender.text))
                        heatbed_temp_tmp(1) = Math.Min(130, Val(sender.text))
                    Case "TextBox29"
                        heatbed_temp(2) = Math.Min(130, Val(sender.text))
                        heatbed_temp_tmp(2) = Math.Min(130, Val(sender.text))
                    Case "TextBox30"
                        heatbed_temp(3) = Math.Min(130, Val(sender.text))
                        heatbed_temp_tmp(3) = Math.Min(130, Val(sender.text))
                    Case "TextBox31"
                        heatbed_temp(4) = Math.Min(130, Val(sender.text))
                        heatbed_temp_tmp(4) = Math.Min(130, Val(sender.text))
                    Case "TextBox32"
                        heatbed_temp(5) = Math.Min(130, Val(sender.text))
                        heatbed_temp_tmp(5) = Math.Min(130, Val(sender.text))
                End Select

            End If
        End If
    End Sub

    Private Sub TextBox3_TextChanged(sender As Object, e As EventArgs) Handles TextBox3.TextChanged, TextBox4.TextChanged, TextBox5.TextChanged, TextBox6.TextChanged, TextBox7.TextChanged, TextBox8.TextChanged

        Dim tempo As String = sender.text.ToString
        If sender.name.ToString.Length > 0 And Not hotend_temp Is Nothing Then
            Dim tag_ As Integer = Val(sender.tag)
            For ir As Integer = 1 To sender.text.ToString.Length - 1
                If Asc(Mid(sender.text.ToString, ir, 1)) <> 8 Then
                    If Asc(Mid(sender.text.ToString, ir, 1)) < 48 Or Asc(Mid(sender.text.ToString, ir, 1)) > 57 Then
                        tempo = hotend_temp_tmp(tag_).ToString()
                    End If
                End If
            Next

            sender.Text = tempo

            If hotend_temps_linked Then
                hotend_temp(0) = Math.Max(0, Math.Min(300, Val(TextBox3.Text)))
                hotend_temp_tmp(0) = Math.Max(0, Math.Min(300, Val(TextBox3.Text)))
                sender.Text = hotend_temp(0)

                For i As Integer = 4 To 8
                    Dim txt As TextBox = Me.Controls("GroupBox1").Controls("TextBox" & i)
                    txt.Text = TextBox3.Text
                Next
            Else
                Select Case sender.name
                    Case "TextBox3"
                        hotend_temp(0) = Math.Min(300, Val(TextBox3.Text))
                        hotend_temp_tmp(0) = Math.Min(300, Val(TextBox3.Text))
                    Case "TextBox4"
                        hotend_temp(1) = Math.Min(300, Val(sender.text))
                        hotend_temp_tmp(1) = Math.Min(300, Val(sender.text))
                    Case "TextBox5"
                        hotend_temp(2) = Math.Min(300, Val(sender.text))
                        hotend_temp_tmp(2) = Math.Min(300, Val(sender.text))
                    Case "TextBox6"
                        hotend_temp(3) = Math.Min(300, Val(sender.text))
                        hotend_temp_tmp(3) = Math.Min(300, Val(sender.text))
                    Case "TextBox7"
                        hotend_temp(4) = Math.Min(300, Val(sender.text))
                        hotend_temp_tmp(4) = Math.Min(300, Val(sender.text))
                    Case "TextBox8"
                        hotend_temp(5) = Math.Min(300, Val(sender.text))
                        hotend_temp_tmp(5) = Math.Min(300, Val(sender.text))
                End Select

            End If
        End If
    End Sub

    Private Sub TextBox20_TextChanged(sender As Object, e As EventArgs) Handles TextBox20.TextChanged,
        TextBox21.TextChanged,
        TextBox22.TextChanged,
        TextBox23.TextChanged,
        TextBox24.TextChanged,
        TextBox25.TextChanged
        If loaded Then
        Else
            Exit Sub
        End If
        Dim tempo As String = sender.text.ToString
        If sender.name.ToString.Length > 0 And Not flowrate Is Nothing Then
            Dim tag_ As Integer = Val(sender.tag)
            For ir As Integer = 1 To sender.text.ToString.Length - 1
                If Asc(Mid(sender.text.ToString, ir, 1)) <> 8 Then
                    If Asc(Mid(sender.text.ToString, ir, 1)) < 48 Or Asc(Mid(sender.text.ToString, ir, 1)) > 57 Then
                        tempo = flowrate_tmp(tag_).ToString()
                    End If
                End If
            Next
            sender.Text = tempo
            If flowrate_linked Then
                flowrate(0) = Math.Max(0, Math.Min(300, Val(TextBox20.Text)))
                flowrate_tmp(0) = Math.Max(0, Math.Min(300, Val(TextBox20.Text)))
                sender.text = flowrate(0)
                For i As Integer = 21 To 25
                    Dim txt As TextBox = Me.Controls("GroupBox1").Controls("TextBox" & i)
                    txt.Text = flowrate(0)
                Next
            Else
                Dim new_val As Double = Math.Max(0, Math.Min(300, Val(sender.text)))
                Select Case sender.name
                    Case "TextBox3"
                        flowrate(0) = new_val
                        flowrate_tmp(0) = new_val
                    Case "TextBox4"
                        flowrate(1) = new_val
                        flowrate_tmp(1) = new_val
                    Case "TextBox5"
                        flowrate(2) = new_val
                        flowrate_tmp(2) = new_val
                    Case "TextBox6"
                        flowrate(3) = new_val
                        flowrate_tmp(3) = new_val
                    Case "TextBox7"
                        flowrate(4) = new_val
                        flowrate_tmp(4) = new_val
                    Case "TextBox8"
                        flowrate(5) = new_val
                        flowrate_tmp(5) = new_val
                End Select

            End If
        End If
    End Sub

    Private Sub PictureBox2_Click(sender As Object, e As EventArgs) Handles PictureBox2.Click
        fans_speed_linked = Not fans_speed_linked
        If fans_speed_linked Then
            PictureBox2.Image = ImageList1.Images(1)

        Else
            PictureBox2.Image = ImageList1.Images(0)
        End If
        For i As Integer = 14 To 18
            Dim txt As TextBox = Me.Controls("GroupBox1").Controls("TextBox" & i)
            txt.ReadOnly = fans_speed_linked
            If fans_speed_linked Then
                txt.Text = TextBox13.Text
            Else
                txt.Text = fan_speeds_tmp(i - 13)
            End If
        Next
    End Sub

    Private Sub PictureBox4_Click(sender As Object, e As EventArgs) Handles PictureBox4.Click
        heatbed_temp_linked = Not heatbed_temp_linked
        If heatbed_temp_linked Then
            PictureBox4.Image = ImageList1.Images(1)

        Else
            PictureBox4.Image = ImageList1.Images(0)
        End If
        For i As Integer = 28 To 32
            Dim txt As TextBox = Me.Controls("GroupBox1").Controls("TextBox" & i)
            txt.ReadOnly = heatbed_temp_linked
            If heatbed_temp_linked Then
                txt.Text = TextBox27.Text
            Else
                txt.Text = heatbed_temp_tmp(i - 28)
            End If
        Next
    End Sub

    Private Sub PictureBox3_Click(sender As Object, e As EventArgs) Handles PictureBox3.Click
        flowrate_linked = Not flowrate_linked
        If flowrate_linked Then
            PictureBox3.Image = ImageList1.Images(1)

        Else
            PictureBox3.Image = ImageList1.Images(0)
        End If
        For i As Integer = 21 To 25
            Dim txt As TextBox = Me.Controls("GroupBox1").Controls("TextBox" & i)
            txt.ReadOnly = flowrate_linked
            If flowrate_linked Then
                txt.Text = TextBox20.Text
            Else
                txt.Text = flowrate_tmp(i - 21)
            End If
        Next
    End Sub

    Private Sub PictureBox1_Click(sender As Object, e As EventArgs) Handles PictureBox1.Click
        hotend_temps_linked = Not hotend_temps_linked
        If hotend_temps_linked Then
            PictureBox1.Image = ImageList1.Images(1)

        Else
            PictureBox1.Image = ImageList1.Images(0)
        End If
        For i As Integer = 4 To 8
            Dim txt As TextBox = Me.Controls("GroupBox1").Controls("TextBox" & i)
            txt.ReadOnly = hotend_temps_linked
            If hotend_temps_linked Then
                txt.Text = TextBox3.Text
            Else
                txt.Text = hotend_temp_tmp(i - 3)

            End If
        Next
    End Sub

    Private Sub TextBox8t_TextChanged(sender As Object, e As EventArgs) Handles TextBox8t.TextChanged

    End Sub

    Private Sub TextBox8t_LostFocus(sender As Object, e As EventArgs) Handles TextBox13.LostFocus, TextBox14.LostFocus, TextBox15.LostFocus, TextBox16.LostFocus, TextBox17.LostFocus, TextBox18.LostFocus,
        TextBox3.LostFocus, TextBox4.LostFocus, TextBox5.LostFocus, TextBox6.LostFocus, TextBox7.LostFocus, TextBox8.LostFocus,
        TextBox3t.LostFocus, TextBox4t.LostFocus, TextBox5t.LostFocus, TextBox6t.LostFocus, TextBox7t.LostFocus, TextBox8t.LostFocus
        'Dim digitsOnly As Regex = New Regex("[^\d]")
        Dim tag_ As Integer = Val(sender.tag)
        If sender.name.contains("1") Then
            sender.Text = fan_speeds_tmp(tag_).ToString()
        ElseIf sender.name.ToString.EndsWith("t") Then
            '
        Else
            sender.Text = hotend_temp_tmp(tag_).ToString()
        End If

    End Sub

    Private Sub SaveUnderToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles SaveUnderToolStripMenuItem.Click

    End Sub

    Private Sub Form1_Shown(sender As Object, e As EventArgs) Handles Me.Shown
        loaded = True
    End Sub

    Private Sub ComboBox1_SelectedIndexChanged(sender As Object, e As EventArgs) Handles ComboBox1.SelectedIndexChanged
        If skip_1 = True Then
            skip_1 = False
            Exit Sub

        End If
        If src_gcode Is Nothing Then
            Label4.Text = ("You must load first a gcode file before edit settings...")
            If Not ComboBox1.SelectedIndex = 0 Then
                skip_1 = True
                ComboBox1.SelectedIndex = 0

            End If
            Exit Sub
        Else
            Select Case ComboBox1.SelectedIndex
                Case 0
                    If slicer_name.Equals("Simplify3D") Then
                        layers = {10, 29, 49, 69, 89, 109}
                    ElseIf slicer_name.Equals("Cura Engine") Then
                        layers = {9, 28, 48, 68, 88, 108}
                    ElseIf slicer_name.Equals("Slic3r - Not yet supported without custom layer gcode..") Then
                        layers = {10, 29, 49, 69, 89, 109}
                    Else
                        layers = {9, 28, 48, 68, 88, 108}
                    End If

                Case 1
                    If slicer_name.Equals("Simplify3D") Then
                        layers = {10, 53, 88, 125, 161, 197}
                    ElseIf slicer_name.Equals("Cura Engine") Then
                        layers = {9, 52, 88, 124, 160, 196}
                    ElseIf slicer_name.Equals("Slic3r - Not yet supported without custom layer gcode..") Then
                        layers = {10, 53, 88, 125, 161, 197}
                    Else
                        layers = {9, 52, 88, 124, 160, 196}
                    End If

            End Select
            UpdateTextBoxLayerValues(layers)
        End If
    End Sub
    Public Sub UpdateTextBoxLayerValues(ByVal layers_() As Integer)
        For i As Integer = 3 To 8
            Me.Controls("GroupBox1").Controls("TextBox" & i & "t").Text = layers_(i - 3)
        Next
    End Sub
End Class
